name: idl-project
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.7.10
  - pytorch=1.7.1
  - numpy=1.19
  - torchvision
  - pip
  - boto3
  - scikit-learn
  - wandb
  - pytest
  - pytest-cov
  - cudatoolkit
  - ipykernel
  - matplotlib
  - black
  - jq
  - make
  - pip:
    - s3fs==0.4.2
    - pylint
    - nibabel
    - git+https://github.com/PyTorchLightning/pytorch-lightning.git
